This project contains multiple Dockerfile versions:

- Dockerfile-nn-xyz reflecting various states of the course demo

In order to use any of them, you can

- rename the corresponding file into the standard name Dockerfile and use the build command 
  docker build -t <tag> .
  
- use the option -f to address the actual Dockerfile within the build command:
  docker build -f Dockerfile-nn-xyz -t <tag> .
