apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise
spec:
  selector:
    matchLabels:
      name: exercise
  template:
    metadata:
      labels:
        name: exercise
    spec:
      containers:
      - name: rest-exercise
        image: gedoplan-seminar/ctr-exercise-rest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
        env:
          - name: MYSQL_SERVICE_HOST
            value: exercise-db
          - name: MYSQL_SERVICE_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: exercise?useSSL=false
          - name: MYSQL_USER
            value: exercise
          - name: MYSQL_PASSWORD
            value: exercise_123
          - name: DATASOURCE
            value: MySQLDS
