apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  exercise-db
spec:
  serviceName: exercise-db
  selector:
    matchLabels:
      name: exercise-db
  volumeClaimTemplates:
    - metadata:
        name: exercise-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Mi
  template:
    metadata:
      labels:
        name:  exercise-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.3
        ports:
        - containerPort: 3306
          name: db
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: rootpassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: exercise-db
                key: password
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: exercise-db
