apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-deployment.yaml
- app-ingress.yaml
- app-service.yaml

commonLabels:
  app.kubernetes.io/name: rest-demo
  app.kubernetes.io/component: app
