# A docker compose file to start a Maria DB
version: '3.1'

services:

  mariadb:
    image: mariadb:10.7.1
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: "seminar"
      MARIADB_USER: "seminar"
      MARIADB_PASSWORD: "seminar"
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"

