apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rest-demo
spec:
  selector:
    matchLabels:
      name: rest-demo
  template:
    metadata:
      labels:
        name:  rest-demo
    spec:
      containers:
      - image:  gedoplan-seminar/ctr-demo-rest
        name:  rest-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8080
          name:  pod-web
        env:
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: rest-demo-db-secret
                key: database
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://rest-demo-db:5432/$(POSTGRES_DATABASE)
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            valueFrom:
              secretKeyRef:
                name: rest-demo-db-secret
                key: user
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rest-demo-db-secret
                key: password

# The environment variables above replace KumuluzEE config values:
#   KUMULUZEE_DATASOURCES0_CONNECTIONURL -> kumuluzee.datasources[0].connection-url
#   KUMULUZEE_DATASOURCES0_USERNAME      -> kumuluzee.datasources[0].username
#   KUMULUZEE_DATASOURCES0_PASSWORD      -> kumuluzee.datasources[0].password
# The necessary driver is part of the demo application already

        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 5
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
