apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rest-demo-db
spec:
  serviceName: rest-demo-db
  selector:
    matchLabels:
      name: rest-demo-db
  volumeClaimTemplates:
    - metadata:
        name: rest-demo-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        name: rest-demo-db
    spec:
      containers:
      - image: postgres:11.4
        imagePullPolicy: IfNotPresent
        name:  db
        ports:
          - name: pod-db
            containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: database
                name: rest-demo-db-secret
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: rest-demo-db-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: rest-demo-db-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: rest-demo-db
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)", "-h", "localhost"]
          initialDelaySeconds: 3
          failureThreshold: 1
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)", "-h", "localhost"]
          initialDelaySeconds: 60
