# A docker compose file to start a Maria DB
version: '3.1'

services:

  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "seminar"
      MYSQL_USER: "seminar"
      MYSQL_PASSWORD: "seminar"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

