apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-demo-db
spec:
  selector:
    matchLabels:
      name: rest-demo-db
  template:
    metadata:
      labels:
        name: rest-demo-db
    spec:
      containers:
      - image: postgres:11.4
        imagePullPolicy: IfNotPresent
        name:  db
        ports:
          - name: pod-db
            containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: restdemo
          - name: POSTGRES_USER
            value: restdemo
          - name: POSTGRES_PASSWORD
            value: restdemo_123
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-volume
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: rest-demo-db
