apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rest-demo
spec:
  template:
    spec:
      containers:
      - name:  rest-demo
        resources:
          limits:
            cpu: 750m
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 10
