# A docker compose file to start a PostgreSQL DB
version: '3.1'

services:

  postgres:
    image: postgres:13.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "seminar"
      POSTGRES_USER: "seminar"
      POSTGRES_PASSWORD: "seminar"

