kumuluzee:
  openapi:
    enabled: false
  datasources:
    - jndi-name: jdbc/demo
      connection-url: jdbc:h2:~/h2/demo
      username: demo
      password: demo
      pool:
        max-size: 20
  health:
    checks:
      data-source-health-check:
        type: readiness
        jndi-name: jdbc/demo
