apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- db-statefulset.yaml
- db-secret.yaml
- db-service.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: db
