kind: Service
apiVersion: v1
metadata:
  name:  rest-demo
spec:
  selector:
    name:  rest-demo
  type:  NodePort
  ports:
  - name:  svc-web
    port:  80
    targetPort:  pod-web
    nodePort: 30101
