apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-demo
spec:
  rules:
  - host: rest-demo.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rest-demo
            port:
              name: svc-web
